# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scoreborde_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 764)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title_time = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_title_time.setFont(font)
        self.label_title_time.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_time.setObjectName("label_title_time")
        self.verticalLayout_3.addWidget(self.label_title_time)
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setSizeIncrement(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_time.setFont(font)
        self.label_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_time.setAutoFillBackground(False)
        self.label_time.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_time.setScaledContents(False)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.verticalLayout_3.addWidget(self.label_time)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                      "color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.font = QFont('Arial', 14)

        self.functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title_time.setText(_translate("MainWindow", "Время"))
        self.label_time.setText(_translate("MainWindow", "00:00"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))


    def functions(self):
        ui.pushButton.clicked.connect(self.set_current_font)

    def set_current_font(self):
        new_size = int((MainWindow.width() / 7 + MainWindow.height() / 7) / 2)
        self.font.setPointSize(new_size)
        self.label_time.setFont(self.font)
        self.label_title_time.setFont(self.font)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
